language: ruby
sudo: false
script: "bundle exec rake spec"
env:
  - CI=true
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
gemfile:
  - Gemfile
notifications:
  recipients:
    - smaginsergey1310@gmail.com
